### ISSUE TITLE
Improvements 1

### ISSUE THREAD

**Issue by Shibu778** [Shibu778/defectpl#1]
# TODO
- [ ] #2
- [x] Take gaussian function in the class to a later point to manage the chronology.
- [x] Line 232 use length variable.
- [x] Line 419 change sum to np.sum
- [ ] #3
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7

**Comment by Shibu778** [comment]
Line 232 use length variable.
